development:
  sessions:
    default:
      database: bacon_asia_development
      hosts:
        - localhost:<%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>
      options:
  options:
test:
  sessions:
    default:
      database: bacon_asia_test
      hosts:
        - localhost:<%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
